name: Deploy Website - with Cache
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
            key: ${{ hashFiles('package-lock.json') }}
            path: '~/.npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
        js-filename-output: ${{ steps.publish-js-filename.outputs.js-filename }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
            key: ${{ hashFiles('package-lock.json') }}
            path: '~/.npm'
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      - name: Publish JS Filename
        id: publish-js-filename
        run: find dist/assets/*.js -type f -execdir echo 'js-filename={}' >> $GITHUB_OUTPUT ';'
      - name: Upload dist files
        uses: actions/upload-artifact@v3
        with:
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
      - name: Output contents
        run: ls
      - name: Output filename
        run: echo '${{ needs.build.outputs.js-filename-output }}'
      - name: Deploy
        run: echo 'Deploying...'
              